-- Table pour stocker tous les signaux bruts récupérés via l'API taapi.io
-- Permet d'analyser a posteriori tous les signaux, même ceux qui ne déclenchent pas d'événement

CREATE TABLE IF NOT EXISTS signaux_bruts (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    dateheure TIMESTAMP NOT NULL,
    rsi14 NUMERIC(6,2),
    rsi5 NUMERIC(6,2),
    bb_upper NUMERIC(18,5),
    bb_lower NUMERIC(18,5),
    bb_mid NUMERIC(18,5),
    ema NUMERIC(18,5),
    close NUMERIC(18,5),
    open NUMERIC(18,5),
    high NUMERIC(18,5),
    low NUMERIC(18,5),
    pattern VARCHAR(50),
    pattern_inverted_hammer BOOLEAN,
    pattern_bullish_engulfing BOOLEAN,
    pattern_bearish_engulfing BOOLEAN,
    pattern_hammer BOOLEAN,
    pattern_hanging_man BOOLEAN,
    pattern_doji BOOLEAN,
    pattern_morning_star BOOLEAN,
    pattern_evening_star BOOLEAN,
    pattern_shooting_star BOOLEAN,
    pattern_piercing BOOLEAN,
    pattern_harami BOOLEAN,
    pattern_harami_cross BOOLEAN,
    pattern_belt_hold BOOLEAN,
    pattern_long_line BOOLEAN,
    pattern_short_line BOOLEAN,
    pattern_high_wave BOOLEAN,
    pattern_stalled BOOLEAN,
    pattern_breakaway BOOLEAN,
    pattern_tasuki_gap BOOLEAN,
    pattern_stick_sandwich BOOLEAN,
    pattern_ladder_bottom BOOLEAN,
    pattern_tristar BOOLEAN,
    pattern_kicking BOOLEAN,
    -- ...add more as needed...
    eventlog TEXT,
    raw_json JSONB,
    created_at TIMESTAMP DEFAULT now(),
    valeur NUMERIC(18,5)
);
