//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public System.DateTime DateHeureDebut { get; set; }
        public Nullable<System.DateTime> DateHeureFin { get; set; }
        public Nullable<decimal> ValeurAchat { get; set; }
        public Nullable<decimal> ValeurVente { get; set; }
        public Nullable<decimal> ValeurCourante { get; set; }
        public Nullable<decimal> QuantiteAchat { get; set; }
        public Nullable<decimal> QuantiteVente { get; set; }
        public string Statut { get; set; }
        public string ID_Exchange { get; set; }
        public decimal FraisAchat { get; set; }
        public decimal FraisVente { get; set; }
        public Nullable<decimal> R0 { get; set; }
        public Nullable<decimal> R1 { get; set; }
        public Nullable<decimal> R2Trailling { get; set; }
        public Nullable<decimal> R2 { get; set; }
        public Nullable<decimal> STOP_COURANT { get; set; }
        public Nullable<decimal> Gain { get; set; }
        public Nullable<decimal> Perte { get; set; }
        public string CodeMethodeTriggerTrade { get; set; }
        public string CodeMethodeSuivi { get; set; }
        public string CodeMethodeSortie { get; set; }
        public string TypeTrade { get; set; }
    }
}
