insert into dbo.oldTradeSet 
--()
   (
   id,
   [Symbol], 
    [DateHeureDebut],
    [DateHeureFin]   ,
    [ValeurAchat]    ,
    [ValeurVente]   ,
    [QuantiteAchat] ,
    [QuantiteVente]  ,
    [Statut]        ,
    [ID_Exchange]  ,
    [FraisAchat]    ,
    [FraisVente]    ,
    [R0]            ,
    [R1]            ,
    [R2Trailling]   ,
    [R2]             ,
    [STOP_COURANT]  ,
    [Gain]         ,
    [Perte]        ,
    [methode_code_methode]
    )
select 
'10000000'+[Id],
    [Symbol], 
    [DateHeureDebut],
    [DateHeureFin]   ,
    [ValeurAchat]    ,
    [ValeurVente]   ,
    [QuantiteAchat] ,
    [QuantiteVente]  ,
    [Statut]        ,
    [ID_Exchange]  ,
    [FraisAchat]    ,
    [FraisVente]    ,
    [R0]            ,
    [R1]            ,
    [R2Trailling]   ,
    [R2]             ,
    [STOP_COURANT]  ,
    [Gain]         ,
    [Perte]        ,
    [methode_code_methode]  from dbo.TradeSet