insert into [dbo].[TradeSet] 
(
    [Symbol]          ,      
    [DateHeureDebut]   ,     
    [DateHeureFin]      ,    
    [ValeurAchat]           ,
    [ValeurVente]           ,
    [ValeurCourante]        ,
    [QuantiteAchat]         ,
    [QuantiteVente]         ,
    [Statut]                ,
    [ID_Exchange]           ,
    [FraisAchat]            ,
    [FraisVente]            ,
    [R0]                    ,
    [R1]                    ,
    [R2Trailling]           ,
    [R2]                    ,
    [STOP_COURANT]          ,
    [Gain]                  ,
    [Perte]                 ,
    [CodeMethodeTriggerTrade] ,
    [CodeMethodeSuivi]        ,
    [CodeMethodeSortie] , 
    [TypeTrade]      
  )
select
    [Symbol]          ,      
    [DateHeureDebut]   ,     
    [DateHeureFin]      ,    
    [ValeurAchat]           ,
    [ValeurVente]           ,
    [ValeurCourante]        ,
    [QuantiteAchat]         ,
    [QuantiteVente]         ,
    [Statut]                ,
    [ID_Exchange]           ,
    [FraisAchat]            ,
    [FraisVente]            ,
    [R0]                    ,
    [R1]                    ,
    [R2Trailling]           ,
    [R2]                    ,
    [STOP_COURANT]          ,
    [Gain]                  ,
    [Perte]                 ,
    [CodeMethodeTriggerTrade] ,
    [CodeMethodeSuivi]   
    [CodeMethodeSortie] , 
    [TypeTrade]      
  from dbo.oldTradeSet3 
